CREATE VIEW Perkon_FiyatGor AS
SELECT
	CASE 
        WHEN M.KOD IS NULL THEN S.STOKKODU
        ELSE M.KOD 
    END AS barkod, M.KOD, MALINCINSI AS isim,
CAST(B.SATISFIYATI1 * B.CARPAN  as decimal(8,2)) AS fiyat, PB1 as doviz
FROM F0101TBLSTOKLAR S 
FULL OUTER JOIN F0101TBLBIRIMLEREX B ON B.STOKNO = S.IND
FULL OUTER JOIN F0101TBLMUASTOKKODU M ON S.IND = M.STOKNO
WHERE S.IND >= 100
AND S.STATUS <> 2
AND S.STOKTIPI IN (0,19)
